### ISSUE TITLE
refreshing the desktop app does not show new issues

### ISSUE THREAD

**Issue by petar** [gov4git/roadmap#19]
I've added https://github.com/gov4git/roadmap/issues/18 which is also under management. But it does not show in the app after refresh or restart.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 23-Jan-24 20:41:27 UTC` by Gov4Git `dev`

### Notice `ibl5rk`
Started managing this issue as Gov4Git concern `19` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by dworthen** [comment]
@petar, are you using the refresh button in the app?
![image](https://github.com/gov4git/roadmap/assets/624870/fbf3b56c-728e-4a18-a4e6-55c67b235a20)

Some insights. On app startup and on manual refresh (ctrl + shift + r) the app load data from its data cache layer for quicker startups. After the app start the cache is refreshed every minute or from clicking the app refresh button. Does the new ballot show up after a minute or after using the refresh button?

I can update the app to kick off a cache refresh right away instead of waiting for the first minute and then every minute after that. 

There is also an open issue to add the most recent refresh time to the app gov4git/gov4git#119 but that has been deprioritized for some of the community deployment work.

**Comment by petar** [comment]
I just tried. I get a "Failed to refresh cache" error when I click the
refresh button, and I don't get an error if I press Cmd+R.
I also get the "Failed to refresh cache" when the up refreshes on its own.
Otherwise all issues and pull requests appear correctly now. (I haven't
updated or restarted even.)

(Refresh timestamp is nice to have, but less important than the
multi-community support, so no rush.)

**Comment by dworthen** [comment]
@petar, Can you close and restart the app and then when the refresh error happens can you attach the full log file here?

**Comment by petar** [comment]
after restarting, i am not getting the error neigher when cmd+r nor when
pressing the refresh button

**Comment by dworthen** [comment]
Closing for now. May reopen if issue resurfaces.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Friday, 26-Jan-24 16:18:23 UTC` by Gov4Git `dev`

### Notice `2r37jm`
This issue, managed as Gov4Git proposal `19`, has been cancelled 🌂

The issue priority tally was `0.000000`.

Refunds issued:

Tally breakdown by user:
